CREATE TABLE PLAYER (
    id_player NUMBER NOT NULL,
    name VARCHAR2(64) NOT NULL,
    PRIMARY KEY(id_player)
);

CREATE TABLE CLASSIFICACAO (
    id_classificacao NUMBER NOT NULL,
    id_player NUMBER NOT NULL,
    score NUMBER NOT NULL,
    PRIMARY KEY(id_classificacao),
    FOREIGN KEY(id_player) REFERENCES PLAYER(id_player)
);


CREATE SEQUENCE SEQ_PLAYER
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE SEQUENCE SEQ_CLASSIFICACAO
START WITH 1
INCREMENT BY 1
NOCACHE;