CREATE USER FRONT_VS_BACK IDENTIFIED BY oracle;

GRANT CONNECT TO FRONT_VS_BACK;
GRANT RESOURCE TO FRONT_VS_BACK;
GRANT DBA TO FRONT_VS_BACK;
GRANT CREATE SESSION TO FRONT_VS_BACK;
GRANT CREATE VIEW TO FRONT_VS_BACK;
GRANT CREATE PROCEDURE TO FRONT_VS_BACK;
GRANT CREATE SEQUENCE TO FRONT_VS_BACK;
GRANT UNLIMITED TABLESPACE TO FRONT_VS_BACK;
GRANT CREATE MATERIALIZED VIEW TO FRONT_VS_BACK;
GRANT CREATE TABLE TO FRONT_VS_BACK;
GRANT GLOBAL QUERY REWRITE TO FRONT_VS_BACK;
GRANT SELECT ANY TABLE TO FRONT_VS_BACK;

ALTER SESSION SET CURRENT_SCHEMA=FRONT_VS_BACK;


CREATE TABLE FRONT_VS_BACK.PLAYER(
	id_player NUMERIC NOT NULL,
	name      VARCHAR(200) NOT NULL,
              PRIMARY KEY(id_player)
);


CREATE SEQUENCE FRONT_VS_BACK.PLAYER_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE TABLE FRONT_VS_BACK.GAME_CHARACTER(
	id_game_character NUMERIC NOT NULL,
	name              VARCHAR(200) NOT NULL,
	                  PRIMARY KEY(id_game_character)
);


CREATE SEQUENCE FRONT_VS_BACK.BATTLE_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE TABLE FRONT_VS_BACK.BATTLE (
    id_battle NUMBER NOT NULL,
    id_winner NUMBER NOT NULL,
    id_loser NUMBER  NOT NULL,
                     PRIMARY KEY(id_battle)
);

-- |id_player|name|
-- |id_game_character|name|
-- |id_battle|DATE|id_winner|id_loser| --> (calcular score com base nas vezes q id_winner aparece)
