

--INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Juquinha');
--INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Pedro');
--INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Gustavo');
--INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Marquinhos');
--INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Bruna');
--INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Marina');
--INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Jose');
INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Rickson');
INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Luiz');
INSERT INTO FRONT_VS_BACK.PLAYER (id_player, name) VALUES (PLAYER_SEQUENCE.NEXTVAL, 'Mateus');

INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (1001, 'Javoso');
INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (1002, 'Reactero');
INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (1003, 'Potugolino');
--INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (CHARACTER_SEQUENCE.NEXTVAL, 'Gpeto');
--INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (CHARACTER_SEQUENCE.NEXTVAL, 'Javiscriptero');
--INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (CHARACTER_SEQUENCE.NEXTVAL, 'HTMLnildo');
--INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (CHARACTER_SEQUENCE.NEXTVAL, 'Oraclildo');
--INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (CHARACTER_SEQUENCE.NEXTVAL, 'SQLino');
--INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (CHARACTER_SEQUENCE.NEXTVAL, 'CSSanindo');
--INSERT INTO FRONT_VS_BACK.GAME_CHARACTER(id_game_character, name) VALUES (CHARACTER_SEQUENCE.NEXTVAL, 'ClouDNildo');


INSERT INTO FRONT_VS_BACK.BATTLE (ID_BATTLE, BATTLE_DATE, ID_WINNER, ID_LOSER) VALUES(BATTLE_SEQUENCE.NEXTVAL, '18/01/2001', 1, 1001);
INSERT INTO FRONT_VS_BACK.BATTLE (ID_BATTLE, BATTLE_DATE, ID_WINNER, ID_LOSER) VALUES(BATTLE_SEQUENCE.NEXTVAL, '18/01/2001', 1, 1003);
INSERT INTO FRONT_VS_BACK.BATTLE (ID_BATTLE, BATTLE_DATE, ID_WINNER, ID_LOSER) VALUES(BATTLE_SEQUENCE.NEXTVAL, '18/01/2001', 2, 1002);
INSERT INTO FRONT_VS_BACK.BATTLE (ID_BATTLE, BATTLE_DATE, ID_WINNER, ID_LOSER) VALUES(BATTLE_SEQUENCE.NEXTVAL, '18/01/2001', 2, 1002);
INSERT INTO FRONT_VS_BACK.BATTLE (ID_BATTLE, BATTLE_DATE, ID_WINNER, ID_LOSER) VALUES(BATTLE_SEQUENCE.NEXTVAL, '18/01/2001', 2, 1003);
INSERT INTO FRONT_VS_BACK.BATTLE (ID_BATTLE, BATTLE_DATE, ID_WINNER, ID_LOSER) VALUES(BATTLE_SEQUENCE.NEXTVAL, '18/01/2001', 2, 1001);
INSERT INTO FRONT_VS_BACK.BATTLE (ID_BATTLE, BATTLE_DATE, ID_WINNER, ID_LOSER) VALUES(BATTLE_SEQUENCE.NEXTVAL, '18/01/2001', 3, 1001);
