# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: epiclabs/docker-oracle-xe-11g
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      ORACLE_USER: system
      ORACLE_PASSWORD: user
      ORACLE_ALLOW_REMOTE: true
      RELAX_SECURITY: 1

    ports:
      - 1521:1521

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080