SELECT nome 
FROM VEM_SER.PAIS 
ORDER BY nome DESC;

SELECT logradouro, cep
FROM VEM_SER.ENDERECO
WHERE UPPER(logradouro) LIKE 'A%';

--Seleciona todos os dados do endereço
SELECT *
FROM VEM_SER.ENDERECO
WHERE cep LIKE '%0';

SELECT *
FROM VEM_SER.ENDERECO
WHERE NUMERO BETWEEN 1 AND 100;

SELECT *
FROM VEM_SER.ENDERECO
WHERE logradouro LIKE 'Rua%' 
ORDER BY cep DESC; 

SELECT COUNT(*) 
FROM ENDERECO;

SELECT ID_CIDADE ,COUNT(*) 
FROM ENDERECO
GROUP BY ID_CIDADE;

