CREATE TABLE VEM_SER.ESTUDANTE (
	id_estudante NUMBER NOT NULL,
	nome VARCHAR2(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) UNIQUE NOT NULL,
	ativo char NOT NULL,
	PRIMARY KEY(id_estudante)
);

CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Luiz Gustavo', TO_DATE('05/01/2005', 'dd-mm-yyyy'), '1111', 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Ana Batata', TO_DATE('02/04/1999', 'dd-mm-yyyy'), '2222', 'N');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Luiz Felipe', TO_DATE('25/02/2002', 'dd-mm-yyyy'), '33333', 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Ricardo Pereira', TO_DATE('15/09/2005', 'dd-mm-yyyy'), '44444', 'N');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Rafael Pedro', TO_DATE('09/11/2000', 'dd-mm-yyyy'), '5555', 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Luis Arthur', TO_DATE('11/12/2000', 'dd-mm-yyyy'), '6666', 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Vitor Rinaldi', TO_DATE('19/11/1980', 'dd-mm-yyyy'), '7777', 'N');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Gustavo Antunes', TO_DATE('09/04/2004', 'dd-mm-yyyy'), '8888', 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Eduardo Benevenuto', TO_DATE('19/02/2006', 'dd-mm-yyyy'), '9999', 'S');
INSERT INTO VEM_SER.ESTUDANTE (ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES
(seq_estudante.nextval, 'Erik Scwartz', TO_DATE('09/10/2010', 'dd-mm-yyyy'), '101010', 'S');


SELECT * FROM VEM_SER.ESTUDANTE
