-- Exercícios de Aula

-- Selecionei toda a tabela para melhor visualização/entendimento dos dados
SELECT * FROM PESSOA p CROSS JOIN CONTATO c; 

SELECT * FROM PESSOA p INNER JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA);

SELECT * FROM PESSOA p
INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
INNER JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)

SELECT * FROM PESSOA p
INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
INNER JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)
INNER JOIN CONTATO c ON (P.ID_PESSOA = C.ID_PESSOA)

SELECT * FROM PESSOA p LEFT JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)

SELECT * FROM PESSOA p ;
SELECT * FROM PESSOA_X_PESSOA_ENDERECO pxpe ;
SELECT * FROM ENDERECO_PESSOA ep ;

SELECT * FROM PESSOA p
LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
LEFT JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)

SELECT * FROM PESSOA p
LEFT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
LEFT JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)
LEFT JOIN CONTATO c ON (P.ID_PESSOA = C.ID_PESSOA)

--Task 03

SELECT * FROM PESSOA P RIGHT JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)

SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
RIGHT JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)

SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
RIGHT JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)
RIGHT JOIN CONTATO c ON (P.ID_PESSOA = C.ID_PESSOA)

SELECT * FROM PESSOA p FULL JOIN CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA)

SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
FULL JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)

SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = PXPE.ID_PESSOA)
FULL JOIN ENDERECO_PESSOA ep ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO)
FULL JOIN CONTATO c ON (P.ID_PESSOA = C.ID_PESSOA)


SELECT * 
FROM PESSOA p
INNER JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON (p.ID_PESSOA = pxpe.ID_PESSOA)
WHERE EXISTS (
    SELECT * 
    FROM PESSOA_X_PESSOA_ENDERECO pxpe2 
    WHERE pxpe2.ID_PESSOA = p.ID_PESSOA
)


